name: publish
on:
  workflow_dispatch:
  schedule:
    - cron: "0 0 1 * *"
  push:
    branches:
      - "master"
jobs:
  publish-image:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        target: ["linux/amd64", "linux/386"]
        arch: ["x86_64-unknown-linux-gnu", "i686-unknown-linux-gnu"]
        exclude:
          - target: "linux/amd64"
            arch: "i686-unknown-linux-gnu"
          - target: "linux/386"
            arch: "x86_64-unknown-linux-gnu"
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Build and push Docker image
        uses: docker/build-push-action@v2
        with:
          push: true
          platforms: ${{ matrix.arch }}
          build-args: |
            RUSTTARGET=${{ matrix.target }}
          tags: |
            ghcr.io/${{ github.repository }}:latest